# Java Maven CircleCI 2.1 configuration file
##

version: 2.1

orbs:
  vulnerability-checker: whitesource/vulnerability-checker@19.7.2
  
workflows:
 test:
   jobs:
      - vulnerability-checker/scan
