jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - artifactory/install
      - artifactory/configure
      - artifactory/build-integration
    environment:
       ARTIFACTORY_URL: "http://http://63.33.198.168/artifactory"
       ARTIFACTORY_API_KEY: "AKCp5ek8GvgJKyTexSgnyA38HqjV3UKVoaykthEuVuSSXqwaggKraNA2YX2vePr784YMYbiBN"
       ARTIFACTORY_USER: "wlo"

orbs:
  artifactory: circleci/artifactory@1.0.0
version: 2.1 


