# Java Maven CircleCI 2.1 configuration file
#

version: 2.1

orbs:
  whitesource-scan: whitesource/whitesource-scan@18.10.2

workflows:
  test:
    jobs:
      - scan:
          directory: ./
       
